### ISSUE TITLE
err

### ISSUE THREAD

**Issue by Tritesson** [Don-Cryptus/Discord-Vanity-Url-Sniper#4]
![image](https://user-images.githubusercontent.com/107753999/177040520-cca2cfa4-95b1-4c03-8bf2-6183f8f87e2a.png)

**Comment by Don-Cryptus** [comment]
thats not even my project 
![image](https://user-images.githubusercontent.com/70039285/177041012-5e72a3a4-f1f1-44ef-82ac-bd733dcf770f.png)

**Comment by Don-Cryptus** [comment]
pip install -r requirements.txt

**Comment by Don-Cryptus** [comment]
![image](https://user-images.githubusercontent.com/70039285/177041069-a80ed98d-67a5-4041-bb0c-5e617167afb9.png)

**Comment by Tritesson** [comment]
i just changed the file location, and settings location.

**Comment by Don-Cryptus** [comment]
seems like you broke your python runtime

**Comment by Don-Cryptus** [comment]
type python -v

**Comment by Don-Cryptus** [comment]
pip install -r requirements.txt

**Comment by Tritesson** [comment]
> pip install -r requirements.txt

I did

**Comment by Don-Cryptus** [comment]
pip list

**Comment by Tritesson** [comment]
> pip list

does discord bot work with tokens?

**Comment by Don-Cryptus** [comment]
no it doesnt you would need to add the bot to each server

**Comment by Tritesson** [comment]
Package                   Version
------------------------- -----------
about-time                3.1.1
aiohttp                   3.7.4.post0
aiosignal                 1.2.0
alive-progress            2.4.1
altgraph                  0.17.2
anyio                     3.6.1
async-generator           1.10
async-timeout             3.0.1
attrs                     21.4.0
beautifulsoup4            4.11.1
Brotli                    1.0.9
bs4                       0.0.1
capmonster-python         1.3.0
certifi                   2022.5.18.1
cffi                      1.15.0
chardet                   4.0.0
charset-normalizer        2.0.12
click                     8.1.3
colorama                  0.4.4
colored                   1.4.3
cryptography              37.0.2
discord                   1.7.3
discord-webhook           0.16.3
discord.py                1.7.3
discum                    1.4.0
emoji-list                0.50
fade                      0.0.9
fake-useragent            0.1.11
filetype                  1.0.13
Flask                     2.1.2
frozenlist                1.3.0
future                    0.18.2
grapheme                  0.6.0
h11                       0.12.0
httpagentparser           1.9.3
httpcore                  0.15.0
httpx                     0.23.0
httpx-socks               0.7.4
idna                      2.10
importlib-metadata        4.11.4
itsdangerous              2.1.2
Jinja2                    3.1.2
keyboard                  0.13.5
lxml                      4.9.0
MarkupSafe                2.1.1
multidict                 6.0.2
outcome                   1.1.0
pefile                    2022.5.30
PIL-Tools                 1.1.0
Pillow                    9.1.1
pip                       20.2.3
psutil                    5.9.1
pyasn1                    0.4.8
pycparser                 2.21
pycryptodome              3.15.0
pyfiglet                  0.8.post1
pyinstaller               5.1
pyinstaller-hooks-contrib 2022.6
pylibcheck                0.2.2
pyOpenSSL                 22.0.0
pyotp                     2.6.0
pyperclip                 1.8.2
pypiwin32                 223
PySocks                   1.7.1
pystyle                   2.0
python-socks              2.0.3
pywin32                   304
pywin32-ctypes            0.2.0
requests                  2.25.1
requests-toolbelt         0.9.1
rfc3986                   1.5.0
selenium                  4.2.0
setuptools                49.2.1
six                       1.16.0
sniffio                   1.2.0
sortedcontainers          2.4.0
soupsieve                 2.3.2.post1
tasksio                   0.0.0
termcolor                 1.1.0
tqdm                      4.64.0
trio                      0.20.0
trio-websocket            0.9.2
txt                       2020.11.12
typing-extensions         4.2.0
ua-parser                 0.10.0
undetected-chromedriver   3.1.5.post4
urllib3                   1.26.9
user-agent                0.1.10
websocket-client          0.59.0
websockets                10.3
Werkzeug                  2.1.2
WMI                       1.5.1
wsproto                   1.1.0
yarl                      1.7.2
zipp                      3.8.0

**Comment by Don-Cryptus** [comment]
it would work with a bot because of rate limit

**Comment by Don-Cryptus** [comment]
you are missing python-dotenv package

**Comment by Don-Cryptus** [comment]
and probably I am 100% sure the configuration 
![image](https://user-images.githubusercontent.com/70039285/177041652-6afcf47c-fd60-4c90-ad60-3408ae9a96b5.png)
